### ISSUE TITLE
Weak DH keys

### ISSUE THREAD

**Issue by ewindisch** [cpuguy83/docker-openvpn#1]
The DH keys in use by this image are weak. Newer versions of OpenSSL and thus OpenVPN clients will refuse to negotiate a connection.

Key generation should be bumped up to 2048bits. In my own fork (https://github.com/ewindisch/docker-openvpn), I've bumped this up and have included HaveGED to speed up key generation and improve overall entropy. I'm happy to make a PR, although my fork has more generally diverged..

**Comment by cpuguy83** [comment]
Thanks, updated!
